app:
  keycloak:
    base-url: http://localhost:9999
    realm: coddefy
    gfesp:
      client: api-financeiro
      secret: JzhASDIYuwcnlYnIQo3xggII2oMm2itF
    
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/financeiro
    username: usr_financeiro
    password: 123!@#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.keycloak.base-url}/realms/${app.keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${app.keycloak.base-url}/realms/${app.keycloak.realm}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
management:
  endpoint:
    refresh:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: '*'
        
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    filter: 'true'
    doc-expansion: none
    tagsSorter: alpha
    path: /docs
    oauth:
      clientId: ${app.keycloak.gfesp.client}
      client-secret: ${app.keycloak.gfesp.secret}
      
documentation:
  oauth2:
    token-url: ${app.keycloak.base-url}/realms/${app.keycloak.realm}/protocol/openid-connect/token
    
logging:
  level:
    org:
      springframework:
        security: INFO
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M
      - %msg%n'
      
