
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/financeiro
    username: usr_financeiro
    password: 123!@#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoint:
    refresh:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: '*'
app:
  teste: 'abc'
