
spring:
  datasource: 
    url: jdbc:mysql://localhost/jpa_example
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoint:
    restart:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: refresh,health
